name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AZURE_WEBAPP_NAME: irs-tax   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.21, 1.22, 1.23]

    steps:
    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.goVer }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get gopkg.in/check.v1

    - name: Build
      run: go build -v .
    
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d .)
    
    - name: Test
      run: go test ./...

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
