name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:

  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        goVer: [1.21, 1.22, 1.23]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.goVer }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get gopkg.in/check.v1

    - name: Build
      run: go build -v .
    
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d .)
    
    - name: Test
      run: go test ./...
